package taiyari;

import javax.swing.JOptionPane;
import taiyari.ObservacionesTratamiento.frmBitacora;
import taiyari.ObservacionesTratamiento.frmCitaAlumno;
import taiyari.Perfiles.frmPerfilAlumno;

//  @author XiCode, desarolladora por:  Jorge García,   Uriel Gonzalez,     Yhostin Ramirez    y Cristopher Escamilla.

public class frmInicioAlumno extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmInicioAlumno.class.getName());

    //Creación del frame:   frmInicioAlumno
    
    public frmInicioAlumno() {
        initComponents();
        Ayudas.maximizarVentana(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnInicioPerfilAlumno = new javax.swing.JButton();
        btnRegistarBitacoraAlumno = new javax.swing.JButton();
        btnSolicitarCitaAlumno = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnInicioAlumno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ventana Alumno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 103, 57));

        jPanel1.setBackground(new java.awt.Color(102, 187, 106));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInicioPerfilAlumno.setText("Perfil");
        btnInicioPerfilAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioPerfilAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicioPerfilAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        btnRegistarBitacoraAlumno.setText("Registrar Emoción");
        btnRegistarBitacoraAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarBitacoraAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistarBitacoraAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, -1, -1));

        btnSolicitarCitaAlumno.setText("Solicitar Cita");
        btnSolicitarCitaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarCitaAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnSolicitarCitaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, -1, -1));

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 790, -1, -1));

        btnInicioAlumno.setText("Inicio");
        btnInicioAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnInicioAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 150, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 1903));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        new Ayudas().volverAInicioSesion(frmInicioAlumno.this);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnRegistarBitacoraAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarBitacoraAlumnoActionPerformed
        new frmBitacora().setVisible(true); this.dispose();
    }//GEN-LAST:event_btnRegistarBitacoraAlumnoActionPerformed

    private void btnSolicitarCitaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarCitaAlumnoActionPerformed
        new frmCitaAlumno().setVisible(true); this.dispose();        
    }//GEN-LAST:event_btnSolicitarCitaAlumnoActionPerformed

    private void btnInicioPerfilAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioPerfilAlumnoActionPerformed
        new frmPerfilAlumno().setVisible(true);     this.dispose();               
    }//GEN-LAST:event_btnInicioPerfilAlumnoActionPerformed

    private void btnInicioAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioAlumnoActionPerformed
        JOptionPane.showMessageDialog(null, "Actualmente se encuentra navegando en esta pantalla.");
    }//GEN-LAST:event_btnInicioAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmInicioAlumno().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnInicioAlumno;
    private javax.swing.JButton btnInicioPerfilAlumno;
    private javax.swing.JButton btnRegistarBitacoraAlumno;
    private javax.swing.JButton btnSolicitarCitaAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
